export default {
  REQUEST_DATA: 'REQUEST_DATA',
  DATA_RECEIVED_SUCCESS: 'DATA_RECEIVED_SUCCESS',
  DATA_RECEIVED_FAIL: 'DATA_RECEIVED_FAIL',
  UPDATE_LIKED_ITEM_IDS: 'UPDATE_LIKED_ITEM_IDS',
  TOGGLE_SOLD_ITEMS: 'TOGGLE_SOLD_ITEMS',
  TOGGLE_LIKED_ITEMS_LIST: 'TOGGLE_LIKED_ITEMS_LIST',
};
